# -*- coding: utf-8 -*-
"""dif_Tiempo.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dE0gng8eN4WDKUsa9Qga7G7uhToH_xNw
"""

import pandas as pd
import matplotlib.pyplot as plt

df_fh = df.copy()

df_fh['fecha_local'] = pd.to_datetime(df_fh['fecha_local'])
df_fh['hora_local'] = pd.to_datetime(df_fh['hora_local'])
df_fh_filtrado = df_fh[(df_fh['magnitud'] > 4.5) & (df_fh['profundidad'] < 70)]
df_fh_filtrado = df_fh_filtrado.sort_values(by=['fecha_local', 'hora_local'])
df_fh_filtrado['dif_tiempo'] = df_fh_filtrado['fecha_local'].diff().fillna(pd.Timedelta(seconds=0)) + df_fh_filtrado['hora_local'].diff().fillna(pd.Timedelta(seconds=0))
plt.figure(figsize=(10, 6))
x = df_fh_filtrado['magnitud']
y = df_fh_filtrado['dif_tiempo'].dt.days
plt.scatter(x, y, color='#e11e30')
plt.xlabel('Magnitud')
plt.ylabel('Días desde el último sismo')
plt.title('Relación entre Magnitud y Días desde el último sismo')
plt.xlim(0, 8.5)
plt.ylim(0, 20)
plt.show()