import pandas as pd
import folium
from folium.plugins import MarkerCluster
from streamlit_folium import folium_static

# -*- coding: utf-8 -*-
"""epicentro.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dKM5wWqd5F8AVShxVi_7PXY_1QT-rO-h
"""

df = pd.read_csv('chile_etl.csv')

df_filtrado = df[(df['depth'] < 70) & (df['magnitude'] > 4.5)]

# Calcular la frecuencia de cada región en el DataFrame filtrado
regiones_mas_afectadas = df_filtrado['codigo_region'].value_counts()
# Crear un mapa centrado en Chile
mapa = folium.Map(location=[-30, -70], zoom_start=5)

# Crear un grupo de marcadores para los sismos
marcadores = MarkerCluster()

# Iterar sobre los registros del DataFrame filtrado
for index, row in df_filtrado.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    magnitud = row['magnitude']
    profundidad = row['depth']
    region = row['codigo_region']
    
    # Agregar un marcador al grupo
    folium.Marker(location=[lat, lon], popup=f"Magnitud: {magnitud}, Profundidad: {profundidad}, Región: {region}").add_to(marcadores)

# Agregar el grupo de marcadores al mapa
marcadores.add_to(mapa)

# Mostrar el mapa
mapa