# -*- coding: utf-8 -*-
"""Mito.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IilZDza9m9Glck10WO-6C8cWX3lK2TUi
"""

plt.figure(figsize=(10, 6))
x = df['magnitud']
y = df['dif_tiempo'].dt.days
plt.xlabel('Magnitud')
plt.ylabel('Días desde el último sismo')
plt.title('Relación entre Magnitud y Días desde el último sismo')
plt.xlim(0, 8.5)
plt.ylim(0, 20)
plt.scatter(x, y)
plt.show()