import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import matplotlib.dates as mdates
import matplotlib.colors as mcolors
from datetime import timedelta
import seaborn as sns

# -*- coding: utf-8 -*-
"""Reporte.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IilZDza9m9Glck10WO-6C8cWX3lK2TUi
"""

# Funciones
df = pd.read_json('datos_chile_etl.json')

df['date'] = pd.to_datetime(df['date'])
df['time'] = pd.to_datetime(df['time'])
sismos_filtrados = df[(df['magnitude'] > 4) & (df['depth'] < 70)]

sismos_filtrados = sismos_filtrados.sort_values(by=['date', 'time'], ascending=False)
ultimo_sismo = sismos_filtrados.iloc[0]
hora_minutos = ultimo_sismo['time'].strftime('%H:%M')
magnitud = ultimo_sismo['magnitude']
profundidad = ultimo_sismo['depth']
#region = ultimo_sismo['region']


print("Último sismo mayor a 4 grados y a menos de 70 km de profundidad:")
print("Hora y minutos:", hora_minutos)
print("Magnitud:", magnitud)
print("Profundidad:", profundidad)
#print("Región:", region)

import folium

df['date'] = pd.to_datetime(df['date'])
df['time'] = pd.to_datetime(df['time'])

sismos_filtrados = df[(df['magnitude'] > 4) & (df['depth'] < 70)]
sismos_filtrados = sismos_filtrados.sort_values(by=['date', 'time'], ascending=False)
ultimo_sismo = sismos_filtrados.iloc[0]
latitud = ultimo_sismo['latitude']
longitud = ultimo_sismo['longitude']
mapa = folium.Map(location=[latitud, longitud], zoom_start=6)

folium.Marker(
    location=[latitud, longitud],
    popup='Último sismo',
    icon=folium.Icon(color='red', icon='info-sign')
).add_to(mapa)

mapa