# -*- coding: utf-8 -*-
"""streamlit1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-BqcRYLkEgCMEByRYKTKRAG2QekuCd9
"""

import pandas as pd
import numpy as np
import requests                     
from datetime import datetime
import matplotlib.pyplot as plt    
import seaborn as sns              
import datetime

"""
Regiones mas afectadas
"""

'''
*************CARGA DE DATOS
'''
df = pd.read_csv('df.csv')

# Calcular la frecuencia de cada región
regiones_mas_afectadas = df['codigo_region'].value_counts()

# Obtener las regiones con la frecuencia más alta
regiones_top = regiones_mas_afectadas.head(6)  # Puedes ajustar el número de regiones que deseas mostrar

# Mostrar las regiones más afectadas
print("Regiones más afectadas:")
print(regiones_top)

"""Las regiones con mas actividad sismicas (con sismo superiores a 4.5 grados a menos de 70 km de profundidad son: 1_Antofagasta: CL-AN, 2_Tarapaca:CL-TA, 3_Coquimbo:CL-CO, 4_'CL-AT': Región de Atacama; las regiones de chile empiezan con CL ."""

df_filtrado = df[(df['depth'] < 70) & (df['magnitude'] > 4.5)]

# Calcular la frecuencia de cada región en el DataFrame filtrado
regiones_mas_afectadas = df_filtrado['codigo_region'].value_counts()

# Obtener las regiones con la frecuencia más alta
regiones_top = regiones_mas_afectadas.head(6)  # Puedes ajustar el número de regiones que deseas mostrar

'''
*********IMPRIME REGIONES MAS AFECTADAS
'''
# Mostrar las regiones más afectadas
print("Regiones más afectadas:")
print(regiones_top)

import folium
from folium.plugins import MarkerCluster

# Crear un mapa centrado en Chile
mapa = folium.Map(location=[-30, -70], zoom_start=5)

# Crear un grupo de marcadores para los sismos
marcadores = MarkerCluster()

# Iterar sobre los registros del DataFrame filtrado
for index, row in df_filtrado.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    magnitud = row['magnitude']
    profundidad = row['depth']
    region = row['codigo_region']
    
    # Agregar un marcador al grupo
    folium.Marker(location=[lat, lon], popup=f"Magnitud: {magnitud}, Profundidad: {profundidad}, Región: {region}").add_to(marcadores)

# Agregar el grupo de marcadores al mapa
marcadores.add_to(mapa)

'''
*********IMPRIME EL MAPA
'''
# Mostrar el mapa
mapa

#1
import numpy as np

# Configurar el tamaño del gráfico
plt.figure(figsize=(10, 6))

# Graficar las barras de frecuencia de las regiones más afectadas con degradado de color
bar_container = plt.bar(regiones_top.index, regiones_top.values, color='#e11e30')

# Obtener el número de barras
num_barras = len(bar_container)

# Generar una lista de valores de transparencia en un rango lineal
transparencias = np.linspace(0.2, 1, num_barras)

# Aplicar transparencia a cada barra
for i, barra in enumerate(bar_container):
    barra.set_alpha(transparencias[i])

# Configurar los ejes y etiquetas
plt.xlabel('Región')
plt.ylabel('Frecuencia')
plt.title('Regiones más afectadas por sismos')

'''
*********IMPRIME EL GRAFICO
'''
# Mostrar el gráfico
plt.show()