# -*- coding: utf-8 -*-
"""Torta.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-s_r5U0JklwmOHQBS3FQ7HJCK1_xv6Vd

KPI en que estacion del año se generan mas sismos
"""

df = pd.read_csv('/content/drive/MyDrive/PF_Sismos/chile_poblacion_es.csv')

df_filtrado = df[(df['magnitud'] > 5) & (df['profundidad'] < 70)]
df['fecha_local'] = pd.to_datetime(df['fecha_local'])
df_filtrado['estacion'] = df_filtrado['fecha_local'].dt.month.apply(lambda x: (x % 12 + 3) // 3)
frecuencia_estaciones = df_filtrado['estacion'].value_counts()
etiquetas = ['Primavera', 'Verano', 'Otoño', 'Invierno']
valores = frecuencia_estaciones.reindex([1, 2, 3, 4])
etiquetas_filtradas = []
valores_filtrados = []
for etiqueta, valor in zip(etiquetas, valores):
    if valor > 0:
        etiquetas_filtradas.append(etiqueta)
        valores_filtrados.append(valor)
fig, ax = plt.subplots()
ax.pie(valores_filtrados, labels=etiquetas_filtradas, autopct='%1.1f%%', startangle=90, colors=[ '#e11e30', '#00BFFF', '#FFA500', '#8B4513'])